# Generated by Django 3.2.9 on 2021-11-15 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211114_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 9, 34, 24, 965223), verbose_name='Join Date'),
        ),
    ]
