# Generated by Django 3.2.9 on 2021-11-15 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 9, 59, 57, 960540), verbose_name='Join Date'),
        ),
    ]
