# Generated by Django 3.2.9 on 2021-11-18 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211118_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 9, 4, 2, 154608), verbose_name='Join Date'),
        ),
    ]
