# Generated by Django 3.2.9 on 2021-11-11 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Huawei', 'Huawei'), ('Oppo', 'Oppo'), ('xiaomi', 'xiaomi'), ('Infinix', 'Infinix'), ('Nokia', 'Nokia'), ('Sony', 'Sony'), ('LG', 'LG'), ('HTC', 'HTC'), ('Lenovo', 'Lenovo'), ('Realme', 'Realme'), ('Honor', 'Honor'), ('ZTE', 'ZTE'), ('Vivo', 'Vivo'), ('Alcatel', 'Alcatel'), ('Asus', 'Asus'), ('Motorola', 'Motorola'), ('Acer', 'Acer')], max_length=100, verbose_name='Brand Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brandslogo', verbose_name='Logo Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_dev', models.SlugField(blank=True, null=True)),
                ('nameDev', models.CharField(max_length=320, verbose_name='Name')),
                ('modeldev', models.CharField(blank=True, max_length=100, null=True)),
                ('networkDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Network')),
                ('announcedDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Announced')),
                ('statusDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Status')),
                ('dimensionsDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Device Dimensions')),
                ('wightDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Device Weight')),
                ('buildDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Build')),
                ('simDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sim')),
                ('displayTypeDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Screen Type')),
                ('displaySizeDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Screen Size')),
                ('displayResDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Screen Resolution')),
                ('oSDev', models.CharField(blank=True, max_length=350, null=True, verbose_name='Android')),
                ('chipsetDev', models.CharField(blank=True, max_length=550, null=True, verbose_name='Chipset')),
                ('cPUDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='CPU')),
                ('cardSlotDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Card Slot')),
                ('internalDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Device Storage')),
                ('mainCameraDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Main Camera')),
                ('main_camera_featuresDev', models.CharField(blank=True, max_length=550, null=True, verbose_name='Features Main Camera')),
                ('main_camera_videoDev', models.CharField(blank=True, max_length=550, null=True, verbose_name='Main Camera Video')),
                ('selfieCameraDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Selfie Camera')),
                ('selfie_camera_videoDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Selfie Camera Video')),
                ('loudspeakerDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Loudspeaker')),
                ('wlanDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='WLAN')),
                ('bluetoothDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bluetooth')),
                ('nfcDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='NFC')),
                ('radioDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Radio')),
                ('usbDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='USB')),
                ('sensorsDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sensors')),
                ('batteryDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Battery Type')),
                ('priceDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Price')),
                ('priceDev_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('priceDev_raya', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price On Raya')),
                ('priceDev_raya_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('priceDev_amazon', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price On Amazon')),
                ('priceDev_amazon_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('imageDev', models.ImageField(blank=True, upload_to='Devices/Devices_img/', verbose_name='Image Device')),
                ('img_dev_full_1', models.ImageField(blank=True, upload_to='Devices/Devices_full_img/', verbose_name='Full Image 1 (or front)')),
                ('img_dev_full_2', models.ImageField(blank=True, upload_to='Devices/Devices_full_img/', verbose_name='Full Image 2 (or back)')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mobile.brand')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mobile.color', verbose_name='Color')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model')),
                ('category', models.CharField(blank=True, choices=[('CompScreen', 'CompScreen'), ('Lcd', 'Lcd'), ('Touch', 'Touch'), ('SubBoard', 'SubBoard'), ('ChargingSocket', 'ChargingSocket'), ('HandfreeSocket', 'HandfreeSocket'), ('Board', 'Board'), ('Battery', 'Battery'), ('BackCamera', 'BackCamera'), ('FCam', 'SelfieCamera'), ('BCover', 'BackGlassCover'), ('Housing', 'Housing')], max_length=50, null=True)),
                ('name', models.CharField(max_length=320, verbose_name='Name')),
                ('quality', models.CharField(blank=True, choices=[('Original', 'Original'), ('HighCopy', 'HighCopy'), ('Copy', 'Copy')], max_length=50, null=True)),
                ('warranty', models.IntegerField(default=0, verbose_name='Warranty')),
                ('code', models.CharField(blank=True, max_length=320, null=True, verbose_name='Code')),
                ('image', models.ImageField(blank=True, upload_to='Spare/Spare_img/', verbose_name='Image Spare')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Price')),
                ('new_or_not', models.BooleanField(default=False, verbose_name='Used Spare')),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.brand')),
                ('device_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Device_sets', to='mobile.device')),
                ('device_same', models.ManyToManyField(to='mobile.Device', verbose_name='Work For Mobiles')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='tags',
            field=models.ManyToManyField(to='mobile.Tag'),
        ),
    ]
