# Generated by Django 3.2.9 on 2021-11-08 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('name', models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Huawei', 'Huawei'), ('Oppo', 'Oppo'), ('xiaomi', 'xiaomi'), ('Infinix', 'Infinix'), ('Nokia', 'Nokia'), ('Sony', 'Sony'), ('LG', 'LG'), ('HTC', 'HTC'), ('Lenovo', 'Lenovo'), ('Realme', 'Realme'), ('Honor', 'Honor'), ('ZTE', 'ZTE'), ('Vivo', 'Vivo'), ('Alcatel', 'Alcatel'), ('Asus', 'Asus'), ('Motorola', 'Motorola'), ('Acer', 'Acer')], max_length=100, verbose_name='Brand Name')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_dev', models.SlugField(blank=True, null=True)),
                ('modeldev', models.CharField(blank=True, max_length=100, null=True)),
                ('nameDev', models.CharField(max_length=320, verbose_name='Name')),
                ('networkDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Network')),
                ('announcedDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Announced')),
                ('statusDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Status')),
                ('dimensionsDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Device Dimensions')),
                ('wightDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Device Weight')),
                ('buildDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Build')),
                ('simDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sim')),
                ('displayTypeDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Screen Type')),
                ('displaySizeDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Screen Size')),
                ('displayResDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Screen Resolution')),
                ('oSDev', models.CharField(blank=True, max_length=350, null=True, verbose_name='Android')),
                ('chipsetDev', models.CharField(blank=True, max_length=550, null=True, verbose_name='Chipset')),
                ('cPUDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='CPU')),
                ('cardSlotDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Card Slot')),
                ('internalDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Device Storage')),
                ('mainCameraDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Main Camera')),
                ('main_camera_featuresDev', models.CharField(blank=True, max_length=550, null=True, verbose_name='Features Main Camera')),
                ('main_camera_videoDev', models.CharField(blank=True, max_length=550, null=True, verbose_name='Main Camera Video')),
                ('selfieCameraDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Selfie Camera')),
                ('selfie_camera_videoDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Selfie Camera Video')),
                ('loudspeakerDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Loudspeaker')),
                ('wlanDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='WLAN')),
                ('bluetoothDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bluetooth')),
                ('nfcDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='NFC')),
                ('radioDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Radio')),
                ('usbDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='USB')),
                ('sensorsDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sensors')),
                ('batteryDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Battery Type')),
                ('priceDev', models.CharField(blank=True, max_length=500, null=True, verbose_name='Price')),
                ('imageDev', models.ImageField(blank=True, upload_to='Devices/Devices_Img/', verbose_name='Image Device')),
                ('img_dev_full_1', models.ImageField(blank=True, upload_to='Devices/Devices_full_pic/', verbose_name='Full Image Device 1')),
                ('img_dev_full_2', models.ImageField(blank=True, upload_to='Devices/Devices_full_pic/', verbose_name='Full Image Device 1')),
                ('color', models.CharField(blank=True, max_length=500, null=True, verbose_name='Color')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mobile.brand')),
            ],
        ),
    ]
