# Generated by Django 3.2.9 on 2021-11-08 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Model')),
                ('category', models.CharField(blank=True, choices=[('CompScreen', 'CompScreen'), ('Lcd', 'Lcd'), ('Touch', 'Touch'), ('SubBoard', 'SubBoard'), ('ChargingSocket', 'ChargingSocket'), ('HandfreeSocket', 'HandfreeSocket'), ('Board', 'Board'), ('Battery', 'Battery'), ('BackCamera', 'BackCamera'), ('SelfieCamera', 'SelfieCamera'), ('BackGlassCover', 'BackGlassCover'), ('Housing', 'Housing')], max_length=50, null=True)),
                ('name', models.CharField(max_length=320, verbose_name='Name')),
                ('quality', models.CharField(blank=True, choices=[('Original', 'Original'), ('HighCopy', 'HighCopy'), ('Copy', 'Copy')], max_length=50, null=True)),
                ('warranty', models.IntegerField(default=0, verbose_name='Warranty')),
                ('code', models.CharField(blank=True, max_length=320, null=True, verbose_name='Code')),
                ('image', models.ImageField(blank=True, upload_to='Spare/Spare_img/', verbose_name='Image Spare')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Price')),
                ('new_or_not', models.BooleanField(default=False, verbose_name='Used Spare')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.brand')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.color')),
                ('device_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Device_sets', to='mobile.device')),
                ('device_same', models.ManyToManyField(to='mobile.Device', verbose_name='Work For Mobiles')),
            ],
        ),
    ]
