# Generated by Django 3.2.9 on 2021-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='color',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Color'),
        ),
    ]
