# Generated by Django 3.2.9 on 2021-11-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0003_auto_20211110_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='brandslogo', verbose_name='Logo Brand'),
        ),
    ]
