# Generated by Django 3.2.9 on 2022-01-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20211216_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spare',
            old_name='local_or_global',
            new_name='local_warranty',
        ),
        migrations.AlterField(
            model_name='spare',
            name='device_same',
            field=models.ManyToManyField(blank=True, null=True, to='mobile.Device', verbose_name='Work For Mobiles'),
        ),
    ]
